
export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FALIURE: 'LOGIN_FALIURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_FALIURE: 'REGISTER_FALIURE',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_FALIURE: 'LOGOUT_FALIURE',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
}
